[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && npm run start"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
